version: "3.8"

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=acme_db
      - POSTGRES_USER=postgres   
      - POSTGRES_HOST=0.0.0.0
      - POSTGRES_PASSWORD=postgres
      
    restart: always 
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: